# -*- coding: utf-8 -*-
"""sympy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ugjz_jU0bN0LJ5UcPKKmZ96L4mgAs6-5
"""

x = 3
print(x)

x = 2,3,4

print(x)

from sympy import Symbol, solve # SymPy라이브러리
x = Symbol('x') # 사용할 기호변수 x 선언

equation = 2 * x -6 # 방정식 풀려면 일차방정식 = 0 형태로 만들어 주어야 함

solve(equation) # x의 해인 3이 출력됨

from sympy import Symbol,solve
import sympy

x = Symbol('x')

a = sympy.Eq(x-2,4)
print(sympy.solve(a))

from sympy import Symbol, solve
x = Symbol('x')
y = Symbol('y')

equation1 = 3 * x+y-2
equation2 = x-2*y-3

solve((equation1,equation2),dict=True)

