# -*- coding: utf-8 -*-
"""역행렬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9BScVcB-LqC9rmT8RsT-ErPDcAg2pfQ
"""

import numpy as np

A = np.array([[1,2],
              [3,4]])

np.linalg.inv(A)

A @ np.linalg.inv(A)