# -*- coding: utf-8 -*-
"""유사역행렬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hvH-PAUTiPlXG8xdXWH_ZqCsIdQjpoVC
"""

import numpy as np

Y = np.array([[0,1],
              [1,-1],
              [2, 1]])

np.linalg.pinv(Y)

np.linalg.pinv(Y) @ Y

