# -*- coding: utf-8 -*-
"""행렬의 내적.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a16i9FtYpZDOwxKHomr1bXgDs_szlKXj
"""

import numpy as np

a = np.array([[1,2,3],
              [2,4,3]])
b = np.array([[3,2,1],
              [1,2,2]])

np.inner(a,b)

import numpy as np

a = np.array([[1,2,3],
              [2,4,3]])
b = np.array([[3,2,1],
              [1,2,2],
              [1,1,3]])

np.inner(a,b)