# -*- coding: utf-8 -*-
"""함수 f(x)=x^2 미분계수 f'(3,0) 계산.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rxcCSgi-fDTaaJCCWXoDdsz90JVfZ80Y
"""

import numpy as np

def numerical_derivative(f,x):
    delta = 1e-5
    diff_x = (f(x+delta)-f(x-delta))/(2*delta)
    return diff_x

def func1(x):
    return x**2

result = numerical_derivative(func1,3.0)
print(result)