# -*- coding: utf-8 -*-
"""함수 f(x)=3xe^x 미분계수 f'(2,0) 계산.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Jebp_9V4fs5-NM-6WVd87_tYFsI2-dS
"""

import numpy as np

def numerical_derivative(f,x):
    delta = 1e-5
    diff_x = (f(x+delta)-f(x-delta))/(2*delta)
    return diff_x

def func2(x):
    return 3*x*(np.exp(x))

result = numerical_derivative(func2,2.0)
print(result)

print(3*np.exp(2) + 3*2*np.exp(2))