# -*- coding: utf-8 -*-
"""행렬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ji-TT2nu1jX0ZXqSamRceMUtt12KdIPo
"""

import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])

print(A)

# 행렬
import numpy as np
import matplotlib.pyplot as plt

heart = np.array([[1,0,0,1,0,0,1],
                  [0,1,1,0,1,1,0],
                  [0,1,1,1,1,1,0],
                  [1,0,1,1,1,0,1],
                  [1,1,0,1,0,1,1],
                  [1,1,1,0,1,1,1]])

plt.xticks([])
plt.yticks([])
plt.imshow(heart,cmap = 'gray')
plt.show()

# 광원
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[77,114,140,191],
              [39,56,46,119],
              [61,29,20,30],
              [151,97,43,26]])

plt.xticks([])
plt.yticks([])
plt.imshow(A,cmap = 'gray',vmin=0,vmax=255)
plt.show()

# RGB
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[[66,199,241]]])

plt.xticks([])
plt.yticks([])
plt.imshow(A)
plt.show()

# 행렬 RGB
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[[255,0,0]],
               [[255,50,0]],
               [[255,255,0]],
               [[0,255,0]],
               [[0,0,255]],
               [[0,5,255]],
               [[100,0,255]]])

B = np.array([[[255,0,0],
               [255,50,0],
               [255,255,0],
               [0,255,0],
               [0,0,255],
               [0,5,255],
               [100,0,255]]])

plt.subplot(1,2,1)
plt.xticks([])
plt.yticks([])
plt.imshow(A)
plt.subplot(1,2,2)
plt.xticks([])
plt.yticks([])
plt.imshow(B)
plt.show()

# 행렬의 합
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[0,1,1,1,0],
              [1,1,1,1,1],
               [0,1,0,0,0]])

B= np.array([[0,0,0,0,0],
              [0,0,0,0,0],
               [0,0,0,1,0]])

C = A+B

plt.xticks([])
plt.yticks([])
plt.imshow(C,cmap = 'gray')
plt.show()
print(C)

import numpy as np

A = np.array([[8,-4],
              [-2,6]])
print(3*A)
print((1/2)*A)

A = np.array([[120,64,64],
              [64,64,120]])

plt.subplot(1,3,1)
plt.xticks([])
plt.yticks([])
plt.imshow(A,cmap='gray',vmin=0,vmax=255)

plt.subplot(1,3,2)
plt.xticks([])
plt.yticks([])
plt.imshow((1/2)*A,cmap='gray',vmin=0,vmax=255)

plt.subplot(1,3,3)
plt.xticks([])
plt.yticks([])
plt.imshow(2*A, cmap = 'gray',vmin=0,vmax=255)

A = np.array([[82,54,82],
              [54,54,54]])

plt.subplot(2,2,1)
plt.xticks([])
plt.yticks([])
plt.imshow((1/4)*A,cmap='gray',vmin=0,vmax=255)

plt.subplot(2,2,2)
plt.xticks([])
plt.yticks([])
plt.imshow((1/2)*A,cmap='gray',vmin=0,vmax=255)

plt.subplot(2,2,3)
plt.xticks([])
plt.yticks([])
plt.imshow(2*A,cmap='gray',vmin=0,vmax=255)

plt.subplot(2,2,4)
plt.xticks([])
plt.yticks([])
plt.imshow(3*A, cmap = 'gray',vmin=0,vmax=255)

# 행렬의 곱
import numpy as np

A = np.array([[1,2,3,4],
              [7,8,9,10]])

B = np.array([[1],
              [2],
              [3],
              [4]])

C = np.array([[1,0],
              [2,0],
              [1,2],
              [2,3]])

D = np.array([[0,1,2,4]])

print(A@B)
# print(B@A) -> shape가 맞지 않아 안됨
print(A@C)
print(C@A)
print(D@B)
print(B@D)

